name = "SBAS"
uuid = "32e3e3ab-304e-4b42-9eeb-18ab18790ea8"
version = "0.1.0"
authors = ["Alex Lasalarie <lasalariea@gmail.com>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Dates = "1.11.0"
LinearAlgebra = "1.12.0"
